graph TD
  TASK-201 --> TASK-202
  TASK-201 --> TASK-203
  TASK-203 --> TASK-204
  TASK-203 --> TASK-UI-270
  TASK-205 --> TASK-206
  TASK-206 --> TASK-UI-261
  TASK-UI-200 --> TASK-UI-201
  TASK-UI-200 --> TASK-UI-210
  TASK-UI-200 --> TASK-UI-220
  TASK-UI-200 --> TASK-UI-230
  TASK-UI-200 --> TASK-UI-250
  TASK-UI-200 --> TASK-UI-260
  TASK-UI-200 --> TASK-UI-270
  TASK-UI-200 --> TASK-TEC-211
  TASK-UI-210 --> TASK-UI-211
  TASK-UI-210 --> TASK-UI-212
  TASK-UI-210 --> TASK-UI-232
  TASK-UI-212 --> TASK-UI-213
  TASK-UI-212 --> TASK-UI-214
  TASK-UI-212 --> TASK-UI-240
  TASK-UI-212 --> TASK-UI-280
  TASK-UI-220 --> TASK-UI-221
  TASK-UI-221 --> TASK-UI-222
  TASK-UI-221 --> TASK-UI-280
  TASK-UI-220 --> TASK-UI-223
  TASK-UI-222 --> TASK-UI-224
  TASK-UI-223 --> TASK-UI-224
  TASK-UI-220 --> TASK-UI-240
  TASK-UI-240 --> TASK-UI-241
  TASK-UI-240 --> TASK-UI-242
  TASK-UI-213 --> TASK-UI-231
  TASK-UI-230 --> TASK-UI-280
  TASK-204 --> TASK-UI-252
  TASK-UI-250 --> TASK-UI-251
  TASK-UI-224 --> TASK-TEC-212
